### ISSUE TITLE
Inicijalni komentari

### ISSUE THREAD

**Issue by ivan-ristovic** [MATF-Software-Verification/2023_Analysis_libfacedetection#1]
Ne secam se svih stavki sa odbrane ali mi se cini da je sve sto smo rekli implementirano. Nekoliko komentara:
- [x] Postoje kopije skripti za pokretanje alata u folderima za svaki alat i u ProjectAnalysisReport folderu. Mozemo da obrisemo duplikate?
- [x] Fali output svakog alata
- Ovo je bonus, ali moze da se uradi `git diff` u odnosu na master projekta, i te izmene staviti kao patch fajl u repozitorijum. Tako znamo sta je razlika u odnosu na master i mozemo obrisati cpp fajlove koji su izmene
- [x] Dodao bih linkove iz PDF-a (npr. na KDE massif-visualizer itd) u Literaturu
- [x] Linkovi u PDF-u (npr. za KDE massif-visualizer) mogu da budu reference, dovoljno je samo ime alata i ref jer URL u paragrafu bas izgleda lose.

Dodajte stavke sa papira koje smo na odbrani napisali ako nesto fali.

**Comment by ivan-ristovic** [comment]
Kako napredujemo sa ovim? Treba da zavrsimo obaveze vezane za seminarske radove uskoro. Nije problem ako ne planirate da uradite ove stavke, samo mi treba informacija da li da upisem sada poene ili da sacekam jos malo.

**Comment by MarijaEric** [comment]
Ispravila sam stavke iz komentara. Takodje sam dodala jos neke elemente u projekat o kojima smo diskutovali na odbrani:

1. Dodala sam alat Callgrind
2. Testirala odvojeno funkcije MyAlloc i MyFree.
3. Testirala sam izmenjene detect-image i detect-camera u kojima testiram samo pozivanje funkcija iz biblioteke za detekciju, bez poziva funkcija iz openCV(osim naravno, fje za ucitavanje slika, koju nisam mogla da izbacim).
4. Popravila sam skripte, i napravila odvojene Makefileove za svaki program.  :)
5.  Izmenila sam i izvestaj shodno novim rezultatima.
